### ISSUE TITLE
Mario's Picross Does Not Save

### ISSUE THREAD

**Issue by phamtq** [JoseJX/analogue-pocket-patches#1]
Problem: The .pocket converted game does not save your progress.
Steps to Recreate:
1. Press Start at title screen
2. Select 'Easy Picross'
3. Select Level 1A
4. Select 'Yes' for Hint and tap 'A' twice
5. Press 'Start', select 'Save', select 'Yes'
6. Press 'A' to return to title screen
7. Quit game through Analogue menu and return to game. No saved progress.

**Comment by JoseJX** [comment]
As far as I know, the Pocket does not save GB only pocket games at this time, saving only works for GBC. I don't think there's anything I can do right now unfortunately.

**Comment by JoseJX** [comment]
This is fixed by Analogue Pocket firmware 1.0A.
