### ISSUE TITLE
Mega Man 2 - Wily's final form never arrives

### ISSUE THREAD

**Issue by buschap** [JoseJX/analogue-pocket-patches#10]
I reached Dr. Wily and defeated his first two forms, but his third form never came on screen. I could still move as normal and the sound was fine. I do not presently have a real cart to check its behavior.

**Comment by JoseJX** [comment]
I'll take a look, but it's going to be a bit, I'm not very good at Mega Man haha

**Comment by JoseJX** [comment]
I wasn't able to reproduce this in the emulator, so I'm not sure if I can fix it. I was able to play through all three stages of Wily without any error or lockups. I checked all of the boxes here: http://www.mmhp.net/Passwords/MMII/ and then cheesed my way through to Wily by overwriting the health (0xA5 to 0xCFD0) whenever I needed more. If you can figure out a way to reproduce this, I'm happy to look into it more.

**Comment by JoseJX** [comment]
treepizzahello tested this on the actual Pocket as well and wasn't able to reproduce. Perhaps it was fixed with the 1.0a Analogue patch?

In any case, please feel free to re-open if you are still having issues. Thanks for reporting!
