### ISSUE TITLE
GTA1 error

### ISSUE THREAD

**Issue by jduckett95** [JoseJX/analogue-pocket-patches#11]
I’ve received an email saying it doesn’t load. I’ve not tested myself - but I will after my shift tonight (~7 hours from now) to confirm.

**Comment by JoseJX** [comment]
I re-tested from a raw ROM and the patch from this github and it works for me. I suspect:

- A long filename, rename it GTA1.pocket or something
- Wrong ROM version, it must be the U version.

**Comment by jduckett95** [comment]
None issue, person had the wrong ROM.
