### ISSUE TITLE
Mole Mania graphics corruption

### ISSUE THREAD

**Issue by lukejohnjones** [JoseJX/analogue-pocket-patches#2]
Problem
- Graphics corruption of the game while using Analogue Pocket and Emulicious

Setup
- Mole Mania verified ROM with MD5: F28ADE3926852A8AD2E449C274683956
- Mole Mania IPS patch
- Generate MoleMania.pocket file with MD5: 792C9B2EBE7A01DA565400780FDE0FD6

Steps to repeat
- Start a new game
- When in-game, press start for the menu
- Exit menu by pressing start again
- Graphics should now be corrupted

**Comment by JoseJX** [comment]
I think I've fixed the issue at the end of the first area, let me know if you have any further issues. I'll leave it open this time.

**Comment by lukejohnjones** [comment]
Looks good to me now! Thanks :-)
