### ISSUE TITLE
Final Fantasy Legend III crashes with Talon's E-Ray.

### ISSUE THREAD

**Issue by pigeonroh** [JoseJX/analogue-pocket-patches#21]
When the Talon vehicle shoots the weapon E-Ray, the game freezes. Analogue OS is still accessible.

I have been able to avoid this crash for most of the game by not equipping the weapon, but the game forces the use of it on the final boss, making it unavoidable and impossible to progress further.

I have attached a save file that quickly allows access to the bug. Select the third save spot, fly around in the ship until an enemy is encountered. The ship will automatically shoot the E-Ray and the game will freeze.

I don't know if this is something you can fix on your end but I thought it might be related. The crash did not occur when I tested it on the Visual Boy Advance emulator. Thank you for everything you are doing for the community.

[Final Fantasy Legend III.zip](https://github.com/JoseJX/analogue-pocket-patches/files/7912803/Final.Fantasy.Legend.III.zip)

**Comment by JoseJX** [comment]
This was a great bug report!

I was easily able to reproduce the issue and found a bit of code that had been decompiled incorrectly by the tools, which ended up referencing one of the registers we need to change to make this work. I've fixed this issue and it should be working fine now! If there are any other issues, please let me know.

Thanks!
