### ISSUE TITLE
Mickey's Speedway USA: Graphic glitches on the road

### ISSUE THREAD

**Issue by Vidnez** [JoseJX/analogue-pocket-patches#23]
The game have graphic glitches on the road.

**Comment by JoseJX** [comment]
I played through the first two levels in the emulator and didn't see any corruption, which means there's a few options:

- I don't know what's corrupted and and missing it
- It's happening in a later level
- It's only happening on the Pocket (I'll test this later today myself)

If you could be a little more specific about what you're seeing, I'd appreciate it! Thanks!

**Comment by Vidnez** [comment]
It's a green flicker layer. In the first track it's present in some parts, in the second track it's all over the track.

https://cdrive.page.link/4eJQzZfG7KJVG8XF9

**Comment by JoseJX** [comment]
It is present with the original cart as well, not a bug in my patch but a bug in Analogue's core. I've filed a bug: https://github.com/frederic-mahe/Analogue-Pocket/issues/49

**Comment by JoseJX** [comment]
Fixed in newer firmware
