### ISSUE TITLE
Super R.C. Pro-Am: Game crashes when you unlock first car

### ISSUE THREAD

**Issue by Vidnez** [JoseJX/analogue-pocket-patches#24]
The game crashes after you unlock the first car (when you collect all the NINTENDO letters through courses)

**Comment by JoseJX** [comment]
Can you test the new build that I just uploaded? I don't have time today to do enough races to check if that fixed the issue.

**Comment by Vidnez** [comment]
It's still crashes with the new build.

**Comment by JoseJX** [comment]
Sorry, it looks like I've missed another spot that needed to be changed. I've uploaded another patch, hopefully this fixes the issue. Thanks for testing!

**Comment by Vidnez** [comment]
It's fixed. Thanks!

**Comment by JoseJX** [comment]
Awesome! Thanks for testing and reporting the issue!
