### ISSUE TITLE
Pokemon Picros crash at "Safari Picross Tutorial"

### ISSUE THREAD

**Issue by larsihasi86** [JoseJX/analogue-pocket-patches#25]
[Pokemon Picross (English v1.2).zip](https://github.com/JoseJX/analogue-pocket-patches/files/7921803/Pokemon.Picross.English.v1.2.zip)

Pokemon Picross (English Version, maybe japanese too, i don't know) crashes after unlocking "Safari Picross" and then entering "Safari Tutorial".
See my video at: https://www.youtube.com/watch?v=z6n6CdJcZV8
I attached my safefile in the zip-file if you need it.

**Comment by JoseJX** [comment]
Thanks, the save file helps! I can reproduce the issue here, I'll look into getting this fixed, thanks for the report!

**Comment by JoseJX** [comment]
I was able to figure out what was wrong and push a fix. Thanks for the save file, it helped to narrow things down immensely!

**Comment by JoseJX** [comment]
Sorry, I forgot to push this fix last night. I've pushed the change now, please let me know if there are any other issues!

**Comment by larsihasi86** [comment]
Thanks a lot! I try to 100% the game. I let you know if i find anything else.
