### ISSUE TITLE
Megami Tensei Gaidan Last Bible II - English Translation

### ISSUE THREAD

**Issue by meunierd** [JoseJX/analogue-pocket-patches#29]
I used `5c426fda8368066cf7e30587876af631` with the English specific patch resulting in a hash of `630a9b71abd0dc57606132b666d524d7` and this simply fails to load. "SD Card Error Couldn't open file for core."

**Comment by JoseJX** [comment]
I don't have an issue with the ROM on my Pocket, it has the same MD5 sum and boots just fine. I would check the following:

- Make sure that the file that's on the SD card has the same MD5
- Make sure that you name the file something relatively short, the pocket has issues with long filenames. I used LastBible2.pocket
- Try another SD card

Hopefully one of these fixes your issue!

**Comment by meunierd** [comment]
It was the file name length, thank you. Is the actual character limit known?

**Comment by JoseJX** [comment]
No, I don't think anyone has tested to find it out, but it might be interesting if you have some free time to find out! :)

Glad you got it resolved! Enjoy the game!
