### ISSUE TITLE
Pokemon Puzzle Challenge - Panel de Pon GB Graphical Issues.

### ISSUE THREAD

**Issue by OngoGablogian** [JoseJX/analogue-pocket-patches#30]
In Pokemon Puzzle Challenge there there is a small easter egg that allows you to play "Panel de Pon GB"  by entering a button combo. More info about this on [The Cutting Room Floor](https://tcrf.net/Pok%C3%A9mon_Puzzle_Challenge).

Unfortunately this mode has some graphical issues that makes it unplayable. I've attached an IPS patch that autoboots into this mode without having to do the button combo for testing purposes.

[Panel de Pon GB - Pokemon Puzzle Challenge (USA, Australia).zip](https://github.com/JoseJX/analogue-pocket-patches/files/7953651/Panel.de.Pon.GB.-.Pokemon.Puzzle.Challenge.USA.Australia.zip)

**Comment by JoseJX** [comment]
Yep, I missed a parameter for a function that sets the video mode register in this mode. I believe it has been fixed. Thanks for reporting!

**Comment by OngoGablogian** [comment]
Thanks!
