### ISSUE TITLE
Kirby's Dream Land DX with Fluffy Repair Service: Basic - Revised HUD ROM

### ISSUE THREAD

**Issue by thaddius** [JoseJX/analogue-pocket-patches#31]
Game freezes after King Dedede is defeated and ending cinematic begins (food falling from King Dedede's castle).

**Comment by JoseJX** [comment]
I think I already fixed this. Did you update your ROM after I released [this patch](https://github.com/JoseJX/analogue-pocket-patches/commit/a8ba502490d7975403011a0464092ec6dca18a69)?

I wasn't able to reproduce this issue with either DX or DX Plus after the update above.
