### ISSUE TITLE
Donkey Kong Land 1 & 3 Glitch when going into bonus barrels

### ISSUE THREAD

**Issue by Zuneman239** [JoseJX/analogue-pocket-patches#34]
Whenever you go into bonus barrels the screen goes to white and then freezes

**Comment by JoseJX** [comment]
Can you give the new patch a try for DK1? I'm not really familiar with these games, but I know this fixed a crash bug when riding the rope to the bonus area. However, I'm not sure that it fixes the issue you're reporting. If it doesn't fix the issue, can you tell me which area to get to and how to reproduce the issue please? Thanks!

**Comment by Zuneman239** [comment]
Sure not a problem I would love to test it for you thanks

Nathan

**Comment by JoseJX** [comment]
I've figured out the issue with DK3 as well, hopefully the updated patch fixes your issue there too! If you could update both of the games and let me know if there are any further issues, I'd really appreciate it, thanks!

**Comment by Zuneman239** [comment]
I'll give it a try first thing after work thanks for all your help

**Comment by Zuneman239** [comment]
I verified that DCL 1 and DL3 is working thank you

**Comment by JoseJX** [comment]
Great, thanks for reporting!
