### ISSUE TITLE
Konami Collection 4: Antartic Adventure freezes at the TIME OVER screen

### ISSUE THREAD

**Issue by Goldanas** [JoseJX/analogue-pocket-patches#35]
Load up Antarctic Adventure from the menu and pick any level, then do not increase your speed and let it run until time runs out. The TIME OVER screen will display and you won't be able to advance or even press all buttons to reboot

**Comment by JoseJX** [comment]
I've fixed this bug, it was another pesky issue where the interrupt register was written with the same value as LCDC in a not so great for us optimization. I've also checked all the other callers for that function and there are no other cases with the same issue, so I'm going to mark this as closed. Please let me know if there are other issues, thanks!
