### ISSUE TITLE
X-Men Mutant Academy (Audio Only?)

### ISSUE THREAD

**Issue by TheAmnesiacKid** [JoseJX/analogue-pocket-patches#39]
Anyone else getting a white screen with audio only when booting the game?

**Comment by JoseJX** [comment]
It's working fine for me here, just re-tested on my Pocket with the patch I've provided here.

Make sure that:

- The MD5 matches the one I've posted
- The filename is short, I used XMen-MA.pocket

Please let me know if it's not working!

**Comment by TheAmnesiacKid** [comment]
My bad. I was using Revision A.

**Comment by JoseJX** [comment]
No worries! Glad you got it working :)
