### ISSUE TITLE
Beavis and Butt-Head - freeze after game over

### ISSUE THREAD

**Issue by admonished** [JoseJX/analogue-pocket-patches#40]
Enter password `FTGBR` and jump into the pit until you run out of lives. After the game over screen it should start scrolling credits, but instead the screen goes grey and you can’t do anything, although the music keeps playing. Not sure if it’s an Analogue hardware bug or not.

**Comment by JoseJX** [comment]
I can reproduce this issue, thanks for reporting! It's a bug in the patch.

**Comment by JoseJX** [comment]
I fixed the issue, it was a typo on my part when I was swapping bytes to have it run on the Pocket. Please test it out and re-open the bug if you have any further issues.
