### ISSUE TITLE
Pop'n TwinBee - Game freezes at Gameover and requires reset

### ISSUE THREAD

**Issue by Mirazozo** [JoseJX/analogue-pocket-patches#41]
Game just hangs forever on a blank screen at gameover, and requires a reset.  

Thanks.

**Comment by JoseJX** [comment]
I believe this is fixed with commit 558a2b1. If there are other issues, please re-open the bug. Thanks for reporting!

**Comment by Mirazozo** [comment]
Very cool!  I confirmed that the update works.  Thank you.
