### ISSUE TITLE
Pokemon Prism - 0.94-0237 - crash when switching to balls pocket

### ISSUE THREAD

**Issue by larsihasi86** [JoseJX/analogue-pocket-patches#42]
Hi, i tested your new Pokemon Prism Patch and found a crash.
You have to play through the first 3 minutes of the game until after you receive your first pokemon and then get an encounter.
If you then open your pack and try to switch to the 'Balls' pocket the game crashes.

I made sure my checksum is right.

I have a link to a short video where i demonstrate the crash:

https://www.youtube.com/watch?v=3M8mD686SiM

Thank you for your great work!

**Comment by JoseJX** [comment]
I believe this is fixed, thanks for reporting!
