### ISSUE TITLE
ROMs that use MBC3 will not save

### ISSUE THREAD

**Issue by JoseJX** [JoseJX/analogue-pocket-patches#45]
The PokePatcher will take care of other Pokemon patches, it has the RTC save fixes built in.

Games that have been fixed and should be tested for issues with saves corrupting due to RTC issues:
- [x] Medarot Kabuto EN
- [x] Medarot Kabuto EN-US
- [x] Medarot Kuwagata EN
- [x] Medarot Kuwagata EN-US  
- [x] Wario Land II (GB version)
- [x] Telefang Speed Translation
- [x] Telefang Power Translation
- [x] Pokemon Red++ - Normal
- [x] Pokemon Red++ - Hard
- [x] Pokemon Brown 
- [x] Pokemon Crystal VN
- [x] Pokemon Prism
- [x] Pokemon Crystal/Silver/Gold for DE/ES
- [x] Pocket Monsters Crystal Version (J) 
- [x] Harvest Moon 1 GBC
- [x] Trade and Battle Card Hero
- [x] Cardcaptor Sakura - Itsumo Sakura-chan to Issho
- [x] Telefang Speed (J)
- [x] Telefang Power (J)

**Comment by pomettini** [comment]
I believe that also both `Medarot - Kabuto Version (English Patch)` and `Medarot - Kabuto Version (US English Patch)` are affected by the same save issue (and possibly the Kuwagata versions as well). Every time I reboot my Pocket, I am prompted with a "New Game" screen every time I boot the game. This does not happen if I quit the game and I load it while the device is on. I've tried several other patches and they seem to be working fine. Any clue @JoseJX?

(Not related to the issue in question, but thank you so much for your work on the patches! You have no idea how much I'm enjoying my new Pocket thanks to all your efforts! <3)

**Comment by JoseJX** [comment]
I believe Medarot is MBC1, so it shouldn't be effected by this. Are you sure that you've updated your pocket to 1.0b? Earlier versions did not save with MBC1 properly.

I'll take a look at it tomorrow if you are on the latest version. Glad you're enjoying the patches!

**Comment by pomettini** [comment]
> Are you sure that you've updated your pocket to 1.0b?

Yes, I checked and my Pocket is on 1.0b. I made a quick test with the Japanese Kabuto version, which is half the size of the patched version (512 KB and 1024 KB respectively) and it does keep the save even when I turn my Pocket off. I wonder if it's something related to the IPS patch or the file size. I also double-checked the hashes of the patched rom files and they are matching. Please let me know if I can be of any help!

**Comment by JoseJX** [comment]
It's unlikely it has anything to do with the IPS patch directly, I suspect that it's related to the build process, perhaps the wrong mapper is getting set. I'll take a look and see if I can reproduce it and let you know. Thanks for the report!

**Comment by JoseJX** [comment]
Okay, I've had a chance to look into this and it appears that the patch converts the game to MBC3, so you were right! Since this game doesn't use RTC, I could easily convert it to MBC5. I've updated the patches, can you test it out a bit to make sure that there aren't any other oddities? Thanks!

**Comment by pomettini** [comment]
> Okay, I've had a chance to look into this and it appears that the patch converts the game to MBC3, so you were right! Since this game doesn't use RTC, I could easily convert it to MBC5. I've updated the patches, can you test it out a bit to make sure that there aren't any other oddities? Thanks!

Thanks a lot @JoseJX! I had a chance to test out the updated patch on the English Kabuto rom and it works perfectly! 👍

**Comment by JoseJX** [comment]
I've patched everything, but I'm not sure I got all of the RTC issues worked out. Please open a new bug if anyone runs into issues with save corruption using these patches. Thanks!
