### ISSUE TITLE
Sutte Hakkun GBC buzzes on Pause Screen

### ISSUE THREAD

**Issue by blinky36** [JoseJX/analogue-pocket-patches#46]
Buzzing audio is present on the pause screen of Sutte Hakkun GBC in the .pocket patched version.

**Comment by JoseJX** [comment]
It does it as well on my flash cart. I assume it's an Analogue Pocket bug if it doesn't do it on real hardware, but I only have a DMG so I can't test it.

**Comment by JoseJX** [comment]
https://github.com/frederic-mahe/Analogue-Pocket/issues/67

**Comment by blinky36** [comment]
I think it is a Pocket issue. I loaded mine through a flash cart (admittedly with one that gets IO errors on Pocket, but with the preload method) and it buzzes, but it does not buzz on my GBA SP nor GBC. Doubt this will ever get addressed specifically in the future.

**Comment by JoseJX** [comment]
I'm not so sure it won't get fixed, there are retail carts with the same issue, which is why I mentioned it in the bug I linked. Hopefully it'll get fixed!
