### ISSUE TITLE
Kirby’s Pinball Land (colorized) crash

### ISSUE THREAD

**Issue by DrAvedi** [JoseJX/analogue-pocket-patches#47]
Thanks for making the patch for this one! I noticed that pressing select will crash to a white screen instead of opening the “save/quit” menu.

not sure if this is a fixable issue, but wanted to try for a solution if possible.

thanks again for making all these patches. I was amazed that the games that I requested were patched in less than 24 hrs!

**Comment by JoseJX** [comment]
No worries! I'm sure it's fixable, it's likely a missed reference on my part. I'll try to get to it tonight!

**Comment by JoseJX** [comment]
It should be fixed by commit cf9b6ab 

Let me know if you run into any other issues!

**Comment by DrAvedi** [comment]
Awesome, thanks so much
