### ISSUE TITLE
Both Tokimeki Memorial patches give an error and refuse to run

### ISSUE THREAD

**Issue by Steven-Pendleton** [JoseJX/analogue-pocket-patches#49]
I tried both of them, but they both give me this error:

SD card error
Couldn't open file for core.

It then returns me to the Pocket's main menu. Used the redump ROMs for both of them.

**Comment by JoseJX** [comment]
Name the file something shorter, this is the error that happens when the filenames are too long or have invalid characters. Try 15 characters or less, something like TokimekiSport.pocket

**Comment by Steven-Pendleton** [comment]
That works, thanks. I had renamed them to be shorter, but apparently it wasn't short enough.

**Comment by JoseJX** [comment]
No worries, glad you got it working!
