### ISSUE TITLE
Game and Watch Gallery 1: Selection Box Missing

### ISSUE THREAD

**Issue by dotdissent** [JoseJX/analogue-pocket-patches#51]
Start Game and Watch Gallery 1 for the first time. Progress past the title screen and the hint screen presented should have a selection box around your options but it is missing. Progressing to the next message does show the selection box.

Example: 
![IMG_20220403_033339~01](https://user-images.githubusercontent.com/17419460/161416907-e45c3f79-76e1-4024-8548-d8beaad6698d.jpg)

Expected: 
![Screenshot_20220403-033540](https://user-images.githubusercontent.com/17419460/161416880-6a958d23-fa38-47b3-a3c5-b74d7d603b48.png)

**Comment by JoseJX** [comment]
Yep, it should be fixed now! Thanks for reporting!

Fixed by commit 3985d92a
