### ISSUE TITLE
Kirby's Block Ball - Ending Graphics Issue

### ISSUE THREAD

**Issue by dotdissent** [JoseJX/analogue-pocket-patches#52]
The first ending achieved at Level 10 has graphical corruption. There is a Gameshark debug menu with an ending viewer that I imagine will help expedite a fix: https://tcrf.net/Kirby%27s_Block_Ball#Debug_Menu

![image](https://user-images.githubusercontent.com/17419460/161680570-1d996329-8b23-400b-9037-3669547ccb75.png)

![image](https://user-images.githubusercontent.com/17419460/161680582-17fc20eb-6b67-4c40-b718-771e390b67bd.png)

**Comment by JoseJX** [comment]
I can reproduce this, I'll update the bug when it's fixed. Thanks for the report!

**Comment by JoseJX** [comment]
This should be fixed now, thanks for the report!

Fixed in cc334aa3
