### ISSUE TITLE
Yoshi’s Cookie (freeze)

### ISSUE THREAD

**Issue by DrAvedi** [JoseJX/analogue-pocket-patches#54]
Thanks for your dedicated work on so many patches!

I just tried Yoshi’s Cookie and am seeing that it freezes when pressing start during gameplay. No further button presses are recognized and the game must be closed and restarted.

**Comment by JoseJX** [comment]
No worries! Sorry about that, I missed a place that needed to be changed. I've fixed the bug in commit cdbc040, and it should be fine now.

Thanks for letting me know!
