### ISSUE TITLE
Link Star Hawk Patch wrong?

### ISSUE THREAD

**Issue by larsihasi86** [JoseJX/analogue-pocket-patches#55]
There seems to be something wrong with the Star Hawk patch.
The Link https://raw.githubusercontent.com/JoseJX/analogue-pocket-patches/main/StarHawk.ips is leading to an empty page.

**Comment by JoseJX** [comment]
Yeah, it appears it was 0 length. Not sure what was going on there. I pushed it again and it appears to be fixed now. Sorry for the trouble!
