### ISSUE TITLE
Star Ocean - La Esfera Azul/Blue Sphere - Spanish translation

### ISSUE THREAD

**Issue by santiis2010** [JoseJX/analogue-pocket-patches#56]
I wanted to make a request but since is just a translation patch for the  Japanese ROM, i cant see any option to request a patch for translated ROM, only Retail Title or maybe as Homebrew?.

Using retro patcher i get this:

Patches not found for these ROMs:
Filename: Star Ocean - Bluesphere (S) [C][!].gbc
MD5: 5f0a9e0ce6c0085af12c787579790f1c

[https://www.romhacking.net/translations/4689/](url)

**Comment by JoseJX** [comment]
Select either "homebrew" or "other region" on the wishing well and submit the request there and I'll get to it when I can!

**Comment by JoseJX** [comment]
The existing patch works fine. I added the MD5 for the Spanish translation to retro patcher.
