### ISSUE TITLE
Battletoads in Ragnarok's World Speedbikes glitch

### ISSUE THREAD

**Issue by Vidnez** [JoseJX/analogue-pocket-patches#58]
In the Speedbikes level when you try to get on the speedbike, nothing happens.

**Comment by JoseJX** [comment]
I wasn't able to reproduce this. I did find a possible bug though, so if you could re-patch and try again, I'd appreciate it!

Thanks!

**Comment by Vidnez** [comment]
It works.

Thanks, now I can get frustrated in that level dying and dying again XD

**Comment by JoseJX** [comment]
Glad it works! Not sure why I wasn't able to reproduce.
