### ISSUE TITLE
Lucky Luke - Desperado Train crash

### ISSUE THREAD

**Issue by Vidnez** [JoseJX/analogue-pocket-patches#59]
In the first level the game crashes when you are in the Saloon entrance and look up.

**Comment by JoseJX** [comment]
It doesn't crash regularly, but it's definitely an Analogue bug, it happens with my flash cart as well in different places with the exact same result.

Opened bug a bug here: https://github.com/frederic-mahe/Analogue-Pocket/issues/83

**Comment by JoseJX** [comment]
Fixed in newer firmware releases
