### ISSUE TITLE
Flintstones - King Rock Treasure Island

### ISSUE THREAD

**Issue by Vidnez** [JoseJX/analogue-pocket-patches#60]
Stage 5 Sea Bottom

There is a part of the stage where you have to go down on a dinosaur shell. The shell doesn't appear.

**Comment by JoseJX** [comment]
Can you retry this? I fixed a call that I missed, perhaps it'll fix the problem. If not, I'll have to reproduce it myself which will take a little while.

**Comment by Vidnez** [comment]
It's fixed. Thank you.

**Comment by JoseJX** [comment]
Awesome! Thanks for testing and reporting the problem!
