### ISSUE TITLE
Hot Wheels – Stunt Track Driver crashes after first tournament race

### ISSUE THREAD

**Issue by Oj5000** [JoseJX/analogue-pocket-patches#61]
Crashes to unresponsive glitched screen after the first Tournament mode race. I've not tried any other modes to see if it does the same thing

**Comment by JoseJX** [comment]
Sorry about that! I missed a call when writing the patch. I've fixed this issue, which also should fix the issue with the HUD being corrupt.

**Comment by Oj5000** [comment]
No need to be sorry, thank you for all your efforts!
