### ISSUE TITLE
Kirby's Dream Land 2 DX pocket patch request

### ISSUE THREAD

**Issue by manichispanic999** [JoseJX/analogue-pocket-patches#63]
Can an .ips be created for the new Kirby's Dreamland 2 DX color hack for the GB Studio?

**Comment by JoseJX** [comment]
I've made a [patch](https://github.com/JoseJX/analogue-pocket-patches#kirbys-dream-land-2-dx-10b) and it should be in the retropatcher soon.

**Comment by manichispanic999** [comment]
> I've made a [patch](https://github.com/JoseJX/analogue-pocket-patches#kirbys-dream-land-2-dx-10b) and it should be in the retropatcher soon.

Thank you!

**Comment by GyroJoe** [comment]
Any chance you could update this for the `v1.1 - 2023-05-11` version of the hack?

romhacking.net doesn't seem to archive the old versions.

**Comment by JoseJX** [comment]
It's been updated!
