### ISSUE TITLE
Shin Pokemon patch mixing

### ISSUE THREAD

**Issue by BestPig** [JoseJX/analogue-pocket-patches#64]
Hello JoseJX,

I think you did some mistake on patch naming.
I tried to apply some Shin Pokemon patch but it's strange.
I took them from this commit -> https://github.com/jojobear13/shinpokered/tree/68c3ea77df49acccbfca9cba62ffc79d109634ad/ips_patches because 1.23 have been removed from the master branch.
But, when I applied the redjp version to the ROM, the hash match the `Shin Pokemon Red` version, and not the `Shin Pokemon Red (J)` as expected.
Then I also try to apply the `shin_pokemon_red_v1.23.ips` and it matches the `Shin Pokemon Green` version instead of the Red one.
So I think you mixed them at some point.

**Comment by JoseJX** [comment]
Yep, I mixed them up, thanks! I've fixed the MD5 sums.

I'm not going to bother updating the patch, the [PokePatcher](http://josejx.net/PokePatcher) should suffice. :)
