### ISSUE TITLE
Kirby's Dream Land 2 (U, E) wrong ROM MD5 listed

### ISSUE THREAD

**Issue by treyturner** [JoseJX/analogue-pocket-patches#7]
Could you please confirm the Kirby's Dream Land 2 (U, E) unpatched MD5? I have `DDB5BFAE32B0CA39CF8AB6C46880126C` on my copy and every copy I've found so far, but you've listed `6421a7fa349a1b7b91ff3c32b5b6ddbb`. Mine is also labelled `(SGB Enhanced)`, is there a non-SGB Enhanced version?

**Comment by treyturner** [comment]
Actually I just noticed `6421a7fa349a1b7b91ff3c32b5b6ddbb` is the IPS MD5, so this probably needs to be updated to my MD5.

**Comment by lukejohnjones** [comment]
The MD5 should be: DDB5BFAE32B0CA39CF8AB6C46880126C

**Comment by JoseJX** [comment]
Yes, I screwed up the MD5, I've corrected it on the page, thanks!
