### ISSUE TITLE
Castlevania Legends crashes in the final cutscene.

### ISSUE THREAD

**Issue by Vidnez** [JoseJX/analogue-pocket-patches#9]
Castlevania Legends crashes in the final cutscene.

**Comment by JoseJX** [comment]
Can you describe what happens? Does it lock up? Is there graphical
corruption?

**Comment by Vidnez** [comment]
In the final scene, you are supposed to see the destruction of the castle, but there is no castle and the game lock up.

**Comment by JoseJX** [comment]
I figured out a way to skip to the end cutscene and can reproduce the castle not being shown.

**Comment by JoseJX** [comment]
I believe this is fixed now, sorry for the wait.
